name: CI Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  run_tests:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/iron'
        cache: 'npm'
    - run: npm ci
    - run: npm run test
