name: CI Tests

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  run_tests:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.13.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run test